# This workflow will build and test a Swift 6.0 project
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Swift 6.0
      run: |
        curl -s https://swift.org/builds/swift-6.0-release/xcode/swift-6.0-RELEASE/swift-6.0-RELEASE-osx.pkg > swift.pkg
        sudo installer -pkg swift.pkg -target /
        swift --version # Verify installation

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
