name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download Swift 6.0 installer
      run: |
        curl -sSL -o swift.pkg https://swift.org/builds/swift-6.0-release/osx/Swift-6.0-osx.pkg
    - name: Install Swift 6.0
      run: installer -pkg swift.pkg -target /
    - name: Clean up
      run: rm swift.pkg
    - name: Set up PATH
      run: echo 'export PATH="/Library/Developer/CommandLineTools/usr/bin:$PATH"' >> $GITHUB_ENV
    - name: Verify Swift version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
